#!/bin/bash
set -e

function cleanup() {
  pushd compose
  docker-compose down --volumes
  docker-compose rm -fs 
  docker system prune -f
  docker volume prune -f
  popd
  # Purge the TF State
  rm -rf ./terraform/.terraform
  rm -rf ./terraform/.terraform.lock.hcl
  rm -rf ./terraform/terraform.tfstate
  rm -rf ./terraform/terraform.tfstate.backup
  rm -rf ./sensitive/*.pem
  rm -rf ./sensitive/*.json
  rm -rf ./sensitive/*.txt
  exit 0
}

trap cleanup SIGKILL SIGINT

function init_compose() {
  pushd compose/
  docker-compose up -d --build

  popd
}

function init_terraform() {
  pushd terraform
  terraform init
  terraform apply -auto-approve

  popd
}


function strip() {
  echo "$1" | tr -d '"'
}

for arg in "$@"
do
    case $arg in
        all)

        init_compose

        echo " "
        echo
        echo "# To verify your install:"
        echo
        echo "docker logs compose-vaultsetup-1"
        echo
        echo "docker logs phpldapadmin-bar"
        echo "docker logs phpldapadmin-foo"
        echo "docker logs phpldapadmin-qux"
        echo
        echo "docker logs openldap-bar"
        echo "docker logs openldap-foo"
        echo "docker logs openldap-qux"
        echo 
        echo "# To login to vault:"
        echo
        echo "export VAULT_ADDR=http://127.0.0.1:8200"
        echo
        echo "export VAULT_TOKEN=$(cat ./sensitive/vault.txt | grep '^Initial' | awk '{print $4}')"
        echo
        echo "vault login"
        echo
        echo "vault read ldap_foo/creds/dynamic_role"
        echo "vault read ldap_bar/creds/dynamic_role"
        echo "vault read ldap_qux/creds/dynamic_role"
        echo
        echo "open http://localhost:8200/ui/vault/secrets"
        echo
        echo "cn=admin,dc=bar,dc=local"
        echo "cn=admin,dc=foo,dc=local"
        echo "cn=admin,dc=qux,dc=local"
        echo
        echo "password is admin"
        echo
        echo "vault login"
        echo
        echo "open http://localhost:8080"
        echo "open http://localhost:8081"
        echo "open http://localhost:8082"
        echo
        echo "./run cleanup"
        echo

        shift
        ;;
        cleanup)
        cleanup
        shift
        ;;
        *)
        echo "cmd not found: try 'all', 'login', or 'cleanup'"
        shift
        ;;
    esac
done














































































































































